# Generated by Django 5.0 on 2023-12-09 03:18

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="дата публикации",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="text",
            field=models.TextField(
                default=datetime.datetime(
                    2023, 12, 9, 3, 18, 14, 884100, tzinfo=datetime.timezone.utc
                ),
                max_length=100000,
                verbose_name="текст",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
    ]
