# Generated by Django 5.0 on 2023-12-09 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_post_created_at_post_text_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=1000, verbose_name="Текст"),
        ),
    ]
