# Generated by Django 5.0 on 2023-12-09 06:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0003_comment_created_at_alter_comment_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарий",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Пост",
                "verbose_name_plural": "Пост",
            },
        ),
        migrations.AlterModelOptions(
            name="reaction",
            options={"verbose_name": "Реакция", "verbose_name_plural": "Реакция"},
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor.fields.RichTextField(max_length=10000, verbose_name="текст"),
        ),
    ]
