# Generated by Django 5.0 on 2023-12-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0006_aboutus_news_delete_reaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "О нас", "verbose_name_plural": "О нас"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Новости",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="news", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="title",
            field=models.CharField(max_length=256, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=256, verbose_name="Заголовок"),
        ),
    ]
