# Generated by Django 5.0 on 2023-12-15 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="logos", verbose_name="Логотип"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, verbose_name="Дата публикации"),
                ),
                (
                    "developer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Разработчик"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Опубликовал"
                    ),
                ),
                (
                    "genre",
                    models.CharField(blank=True, max_length=100, verbose_name="Жанр"),
                ),
                (
                    "platforms",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Платформа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Игра",
                "verbose_name_plural": "Игра",
            },
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Имя")),
                (
                    "office_country",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Офис страны"
                    ),
                ),
                (
                    "total_prize_found",
                    models.IntegerField(blank=True, verbose_name="Общий призовой фонд"),
                ),
                (
                    "hour_watching",
                    models.TimeField(blank=True, verbose_name="Часов просмотров"),
                ),
                (
                    "time_in_live",
                    models.TimeField(blank=True, verbose_name="Часов в эфире"),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организация",
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="имя")),
            ],
            options={
                "verbose_name": "Спонсор",
                "verbose_name_plural": "Спонсор",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Описание"
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="Регион"),
                ),
                (
                    "site_link",
                    models.URLField(blank=True, verbose_name="Ссылка на сайт"),
                ),
                (
                    "sponsor",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organizations",
                        to="statistic.sponsor",
                        verbose_name="Спонсор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организация",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="Регион"),
                ),
                (
                    "founded",
                    models.DateField(blank=True, verbose_name="Дата основания"),
                ),
                (
                    "total_prize",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="Общие призовые"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="teams",
                        to="statistic.game",
                        verbose_name="дисциплина",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="teams",
                        to="statistic.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="teams",
                        to="statistic.sponsor",
                        verbose_name="Спонсор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команда",
            },
        ),
        migrations.CreateModel(
            name="Tournaments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "event_date",
                    models.DateTimeField(blank=True, verbose_name="Дата ивента"),
                ),
                (
                    "type_platform",
                    models.CharField(
                        blank=True,
                        choices=[("mobile", "mobile"), ("pk", "pk")],
                        max_length=100,
                        verbose_name="Платформа",
                    ),
                ),
                (
                    "prize_fond",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="Призовой фонд"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активно"),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tournaments",
                        to="statistic.organizer",
                        verbose_name="Организация",
                    ),
                ),
            ],
        ),
    ]
