# Generated by Django 5.0 on 2023-12-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistic", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name": "Игры", "verbose_name_plural": "Игры"},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "Организации",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.AlterModelOptions(
            name="organizer",
            options={
                "verbose_name": "Организаторы",
                "verbose_name_plural": "Организаторы",
            },
        ),
        migrations.AlterModelOptions(
            name="sponsor",
            options={"verbose_name": "Спонсоры", "verbose_name_plural": "Спонсоры"},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Команды", "verbose_name_plural": "Команды"},
        ),
        migrations.AlterModelOptions(
            name="tournaments",
            options={"verbose_name": "Турниры", "verbose_name_plural": "Турниры"},
        ),
        migrations.AlterField(
            model_name="game",
            name="platforms",
            field=models.CharField(
                choices=[
                    ("windows", "windows"),
                    ("macos", "macos"),
                    ("linux", "linux"),
                    ("mobile", "mobile"),
                    ("console", "console"),
                ],
                default="windows",
                max_length=300,
                verbose_name="Платформа",
            ),
        ),
    ]
