# Generated by Django 4.2.8 on 2023-12-20 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("statistic", "0002_alter_game_options_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="developer",
        ),
        migrations.RemoveField(
            model_name="game",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="game",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="team",
            name="founded",
        ),
        migrations.RemoveField(
            model_name="team",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="team",
            name="sponsor",
        ),
        migrations.RemoveField(
            model_name="tournaments",
            name="organizer",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Organizer",
        ),
        migrations.DeleteModel(
            name="Sponsor",
        ),
    ]
