# Generated by Django 4.2.8 on 2023-12-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistic", "0003_remove_game_developer_remove_game_publisher_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="genre",
        ),
        migrations.AlterField(
            model_name="game",
            name="platforms",
            field=models.CharField(
                choices=[("pk", "pk"), ("mobile", "mobile"), ("console", "console")],
                default="pk",
                max_length=300,
                verbose_name="Платформа",
            ),
        ),
    ]
