# Generated by Django 4.2.8 on 2023-12-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistic", "0005_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to="logo", verbose_name="Логотип"
            ),
        ),
    ]
