# Generated by Django 4.2.8 on 2023-12-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistic", "0006_team_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournaments",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="tournaments", verbose_name="Изображение"
            ),
        ),
    ]
